# Generated by Django 5.1.3 on 2024-11-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_rename_image_request_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'Принято в работу'), ('completed', 'Выполнено')], default='new', max_length=20),
        ),
    ]
