# Generated by Django 5.1.3 on 2024-11-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_delete_studiorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
