# Generated by Django 5.1.3 on 2024-11-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
