# Generated by Django 5.1.3 on 2024-11-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_studiorequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudioRequest',
        ),
    ]
